### PR TITLE
Added mgob (MongoDB backup) chart

### PR DESCRIPTION
**Pull request by endrec**
This is a rework of the mgob chart available at https://github.com/stefanprodan/mgob/tree/master/chart

### CODE REVIEW

**Review by ClaudioConsolmagno — COMMENTED** [review]
Hey, could you point out any substantial changes to the original charts that you had to make?

**Comment by ClaudioConsolmagno** [comment]
Thanks Endre. There's still some linting errors, is that fine?

**Comment by endrec** [comment]
> There's still some linting errors, is that fine?

It seems those are in the test, not the chart. :disappointed: For some reason KinD (K8S in docker) does not like the persistent volumes the chart would like to create. I would not fix them now, I've already put too much effort into it.

**Comment by ClaudioConsolmagno** [comment]
Alright

**Review by ClaudioConsolmagno — APPROVED** [review]

**Pull request merged**
