### PR TITLE
Introducing config for encryption

### PR DESCRIPTION
**Pull request by endrec**

### CODE REVIEW

**Review by jsgriffin — APPROVED** [review]

**Comment by jsgriffin** [comment]
Why does the build fail?

**Comment by endrec** [comment]
> Why does the build fail?

This time it failed because I forgot to update the README. It will fail again, as it references an image version which is not released yet. 
And then it will fail because of an issue with persistent volumes in KinD (K8S in Docker).

**Comment by endrec** [comment]
The chart reference to an image, which can be released from this PR: https://github.com/stefanprodan/mgob/pull/122

**Comment by jsgriffin** [comment]
Nice Go 👍

**Review by ClaudioConsolmagno — APPROVED** [review]

**Pull request merged**
